Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "ubuntu/bionic64"
  c.vm.hostname = "default-macchinapazza.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-Chef-default-macchinapazza-405ae069-42a8-4b2b-82d7-c13f5f1066c2"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
