Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "ubuntu/bionic64"
  c.vm.hostname = "default-macchinapazza.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-Chef-default-macchinapazza-3ac7de76-db1c-482f-8b31-6acfd425e8b6"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
