Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/centos-7"
  c.vm.hostname = "eugenio-centos-7.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/Users/giosuemanzo/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-primo_esercizio-eugenio-centos-7-b334e645-9fda-4863-b5e7-4ec7c677d0f3"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
