Vagrant.configure("2") do |config|
  config.vm.box = "almalinux/9"

  config.vm.define "chserver" do |chserver|
    chserver.vm.hostname = "chserver"
    chserver.vm.network "private_network", ip: "192.168.1.10"
    chserver.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
    end
  end

  config.vm.define "chclient" do |chclient|
    chclient.vm.hostname = "chclient"
    chclient.vm.network "private_network", ip: "192.168.1.11"
    chclient.vm.network "forwarded_port", guest: 8080, host: 8080
    chclient.vm.network "forwarded_port", guest: 50000, host: 50000
    chclient.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
    end
  end

  config.vm.define "chwork" do |chwork|
    chwork.vm.hostname = "chwork"
    chwork.vm.network "private_network", ip: "192.168.1.12"
    chwork.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
    end
  end
end
