Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/centos-10"
  c.vm.hostname = "eugenio-centos-10.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/Users/giosuemanzo/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-primo_esercizio-eugenio-centos-10-f7f74cbc-48ec-4434-93ed-28bc59c56265"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
