Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/ubuntu-2404"
  c.vm.hostname = "eugenio-ubuntu-2404.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/Users/giosuemanzo/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-primo_esercizio-eugenio-ubuntu-2404-0502bda4-2d44-49ec-bb1b-9d6a4b48499f"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
